# Generated by Django 5.2 on 2025-09-14 14:15

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='account_number',
            field=models.BigIntegerField(default=accounts.models.generate_account_number, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='account_plan',
            field=models.CharField(choices=[('queen', 'Queen'), ('king', 'King'), ('knight', 'Knight')], default='queen', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('savings', 'Savings'), ('current', 'Current')], default='savings', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, default='Unknown'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='residency_status',
            field=models.CharField(choices=[('indian', 'Indian'), ('nri', 'NRI')], default='indian', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='virtual_card_number',
            field=models.BigIntegerField(default=accounts.models.generate_virtual_card, unique=True),
        ),
    ]
