# Generated by Django 5.2 on 2025-09-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='occupation',
            field=models.CharField(choices=[('student', 'Student'), ('employee', 'Employee'), ('business', 'Business'), ('other', 'Other')], default='student', max_length=15),
        ),
    ]
