# Generated by Django 5.2 on 2025-09-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_marital_status_customuser_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
    ]
