# Generated by Django 5.2 on 2025-09-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_city_customuser_ifsc_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='upi_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
