# Generated by Django 5.2 on 2025-09-15 17:31

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_city_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='kyc_doc',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.user_kyc_path),
        ),
    ]
